### ISSUE TITLE
Add usage to README.md

### ISSUE THREAD

**Issue by jpolley** [ActiveCampaign/qa-configurator#1]
EDIT

**Comment by ibalosh** [comment]
hey @jpolley 

thanks for doing this. I was planning to update the docs, but I did not have yet time to get to it.
However, if you would like to add it, please add it to wiki pages in similar format as on [postmark.js](https://github.com/wildbit/postmark.js/wiki/Getting-Started) library.

I will update the readme.md once I get to this repo.

**Comment by jpolley** [comment]
@ibalosh I just now realized that configurator is a public repo 🤦🏻‍♂️. I assumed that it was an an _internal_ tool. If it is an external tool, then I will need to better understand how to handle setup for the [SECRET_PASSWORD] before I post to the Wiki. In my write up above I said: 
> [SECRET_PASSWORD] is located in 1Password under "QA - Tests config file credentials"

**Comment by jpolley** [comment]
Usage page added to the Wiki: https://github.com/wildbit/configurator/wiki/Usage

**Comment by ibalosh** [comment]
tx!
